on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  iOS:
    name: Run iOS Tests
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
      MINT_PATH: ${{ github.workspace }}/mint
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 8']#
    steps:
      - name: Force Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Clean Dependencies
        run: tuist dependencies clean
      - name: Fetch Dependencies
        run: tuist dependencies fetch
      - name: Create Workspace
        run: tuist generate
      - name: Testing iOS with Device - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "MobileTestMarvel.xcworkspace" -scheme "MobileTestMarvel" -destination "${{ matrix.destination }}" clean test | xcpretty
      - name: Run Danger - ${{ github.head_ref }} to - ${{ github.base_ref }}
        run: bundle exec danger --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
